version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: cs188-web
    working_dir: /home/docker-dev/web
    command: npm start
    volumes:
      - .:/home/docker-dev
      - /home/docker-dev/web/node_modules
    environment:
      - PORT=3000
      - DEBUG=web:*
    ports:
      - "3000:3000"
